# Generated by Django 3.1.7 on 2021-03-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregaarticulopromocional',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
